version: "3.9"
services:
  redis:
    image: redis
    container_name: credit-redis
    ports:
      - "6379:6379"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 60s

  postgres:
    image: postgres
    container_name: credit-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
