spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.h2.Driver
    defer-datasource-initialization: true
    generate-ddl: true

  data:
    redis:
      url: redis://localhost:6379
  datasource:
    url: jdbc:h2:mem:testdb;MODE=POSTGRESQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DATABASE_TO_LOWER=TRUE;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: password


